const {
  getRandomLongitude,
  getRandomLatitude,
} = require("../utils/google-maps/google-maps.utils");

export const hostMarkers = [
  {
    uid: "1a2b3c4d",
    lat: -41.286,
    lng: 174.766,
    foodType: "Thai",
    address: "123 Cuba Street, Wellington",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 20 2024",
    time: "5:30 PM",
  },
  {
    uid: "5e6f7g8h",
    lat: -41.29,
    lng: 174.772,
    foodType: "French",
    address: "456 Lambton Quay, Wellington",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Exquisite French dishes crafted with finesse and elegance, showcasing the rich culinary heritage of France.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 75,
    hostDisplayName: "Susie",
    date: "Jun 13 2024",
    time: "12:00 PM",
  },
  {
    uid: "9i0j1k2l",
    lat: -41.294,
    lng: 174.773,
    foodType: "Vietnamese",
    address: "789 Courtenay Place, Wellington",
    maxGuestSpots: 6,
    guestSpotsLeft: 6,
    description:
      "Authentic Vietnamese delicacies bursting with flavors, combining fresh herbs, spices, and vibrant ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Emily",
    date: "Jun 15 2024",
    time: "5:00 PM",
  },
  {
    uid: "3m4n5o6p",
    lat: -41.288,
    lng: 174.778,
    foodType: "Colombian",
    address: "321 Willis Street, Wellington",
    maxGuestSpots: 3,
    guestSpotsLeft: 1,
    description:
      "Savor the taste of Colombian cuisine, featuring hearty dishes influenced by diverse regional flavors.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Chris",
    date: "Jun 02 2024",
    time: "6:15 PM",
  },
  {
    uid: "7q8r9s0t",
    lat: -41.285,
    lng: 174.775,
    foodType: "Thai",
    address: "654 Featherston Street, Wellington",
    maxGuestSpots: 8,
    guestSpotsLeft: 4,
    description:
      "Indulge in the vibrant and spicy flavors of Thai cuisine, prepared with a perfect balance of sweet, sour, and savory.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "P Lot",
    date: "Jun 25 2024",
    time: "5:45 PM",
  },
  {
    uid: "1u2v3w4x",
    lat: -41.283,
    lng: 174.773,
    foodType: "French",
    address: "987 Victoria Street, Wellington",
    maxGuestSpots: 7,
    guestSpotsLeft: 7,
    description:
      "Experience the artistry of French gastronomy, with refined dishes that showcase culinary mastery and sophistication.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Jean-Pierre",
    date: "Jun 22 2024",
    time: "12:30 PM",
  },
  {
    uid: "5y6z7a8b",
    lat: -41.282,
    lng: 174.776,
    foodType: "Vietnamese",
    address: "654 Taranaki Street, Wellington",
    maxGuestSpots: 2,
    guestSpotsLeft: 2,
    description:
      "Discover the fresh and vibrant flavors of Vietnamese cuisine, featuring a harmonious blend of herbs, spices, and textures.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 100,
    hostDisplayName: "Linh",
    date: "Jun 29 2024",
    time: "7:00 PM",
  },
  {
    uid: "9c0d1e2f",
    lat: -41.281,
    lng: 174.774,
    foodType: "Colombian",
    address: "321 Ghuznee Street, Wellington",
    maxGuestSpots: 5,
    guestSpotsLeft: 0,
    description:
      "Taste the authentic flavors of Colombian cuisine, with dishes that reflect the country's diverse cultural influences.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Juan",
    date: "Jun 20 2024",
    time: "7:30 PM",
  },
  {
    uid: "3g4h5i6j",
    lat: -41.28,
    lng: 174.777,
    foodType: "Thai",
    address: "789 Lambton Quay, Wellington",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the bold and aromatic flavors of Thai cuisine, featuring a harmonious blend of spices and fresh ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Somsak",
    date: "Jun 01 2024",
    time: "8:00 PM",
  },
  {
    uid: "7k8l9m0n",
    lat: -41.279,
    lng: 174.775,
    foodType: "French",
    address: "456 Cuba Street, Wellington",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the elegance of French cuisine, with dishes that showcase culinary finesse and timeless flavors.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Marie",
    date: "Jun 15 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4e",
    lat: 35.6151,
    lng: -82.5515,
    foodType: "Italian",
    address: "456 Main Street, Ashelville",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4f",
    lat: 35.5951,
    lng: -82.5515,
    foodType: "Mexican",
    address: "789 Elm Street, Ashelville",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4g",
    lat: 35.5951,
    lng: -82.5415,
    foodType: "American",
    address: "321 Oak Street, Ashelville",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4h",
    lat: 35.6251,
    lng: -82.5515,
    foodType: "Japanese",
    address: "654 Pine Street, Ashelville",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4i",
    lat: 35.5951,
    lng: -82.5225,
    foodType: "Indian",
    address: "987 Maple Street, Ashelville",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4d",
    lat: 35.5851,
    lng: -82.5515,
    foodType: "Thai",
    address: "123 Cuba Street, Ashelville",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4j",
    lat: 35.6051,
    lng: -82.5515,
    foodType: "Greek",
    address: "789 Olive Street, Ashelville",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4k",
    lat: 35.5951,
    lng: -82.5615,
    foodType: "Chinese",
    address: "456 Walnut Street, Ashelville",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4l",
    lat: 35.5951,
    lng: -82.5315,
    foodType: "Spanish",
    address: "321 Cherry Street, Ashelville",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Indulge in the vibrant flavors of Spanish cuisine, with dishes that showcase the richness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4m",
    lat: 35.6151,
    lng: -82.5415,
    foodType: "Mexican",
    address: "654 Elm Street, Ashelville",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Experience the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Alejandro",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4n",
    lat: 35.6051,
    lng: -82.5615,
    foodType: "Italian",
    address: "987 Walnut Street, Ashelville",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Giuseppe",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4o",
    lat: 35.5951,
    lng: -82.5715,
    foodType: "Indian",
    address: "123 Maple Street, Ashelville",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Priya",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4p",
    lat: 35.5851,
    lng: -82.5515,
    foodType: "Thai",
    address: "456 Cuba Street, Ashelville",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Arisara",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4q",
    lat: 35.5951,
    lng: -82.5615,
    foodType: "Mexican",
    address: "789 Elm Street, Ashelville",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4r",
    lat: 35.5951,
    lng: -82.5315,
    foodType: "Spanish",
    address: "321 Cherry Street, Ashelville",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Indulge in the vibrant flavors of Spanish cuisine, with dishes that showcase the richness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
  {
    uid: "1a2b3d4z",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Greek",
    address: "789 Olive Street, Atlanta",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Experience the flavors of Greek cuisine, with dishes that showcase the freshness of Mediterranean ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Maria",
    date: "Jun 10 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4aa",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Chinese",
    address: "456 Walnut Street, Seattle",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the diverse flavors of Chinese cuisine, with dishes that showcase the art of wok cooking.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Li",
    date: "Jun 20 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4t",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Italian",
    address: "123 Main Street, New York",
    maxGuestSpots: 4,
    guestSpotsLeft: 2,
    description:
      "Authentic Italian dishes made with love and passion, showcasing the flavors of Italy.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 70,
    hostDisplayName: "Giovanni",
    date: "Jun 02 2024",
    time: "7:00 PM",
  },
  {
    uid: "1a2b3d4u",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Mexican",
    address: "789 Elm Street, Los Angeles",
    maxGuestSpots: 6,
    guestSpotsLeft: 4,
    description:
      "Savor the vibrant and spicy flavors of Mexican cuisine, with dishes inspired by traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 50,
    hostDisplayName: "Carlos",
    date: "Jun 25 2024",
    time: "6:30 PM",
  },
  {
    uid: "1a2b3d4v",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "American",
    address: "321 Oak Street, Chicago",
    maxGuestSpots: 8,
    guestSpotsLeft: 6,
    description:
      "Experience the flavors of classic American cuisine, with dishes that celebrate the rich culinary heritage of the United States.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 40,
    hostDisplayName: "Sarah",
    date: "Jun 22 2024",
    time: "12:00 PM",
  },
  {
    uid: "1a2b3d4w",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Japanese",
    address: "654 Pine Street, San Francisco",
    maxGuestSpots: 4,
    guestSpotsLeft: 1,
    description:
      "Indulge in the artistry of Japanese cuisine, with dishes that showcase precision and balance.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 90,
    hostDisplayName: "Yuki",
    date: "Jun 15 2024",
    time: "7:30 PM",
  },
  {
    uid: "1a2b3d4x",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Indian",
    address: "987 Maple Street, Houston",
    maxGuestSpots: 6,
    guestSpotsLeft: 3,
    description:
      "Experience the vibrant and aromatic flavors of Indian cuisine, with dishes that showcase a rich tapestry of spices and ingredients.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 80,
    hostDisplayName: "Raj",
    date: "Jun 19 2024",
    time: "8:00 PM",
  },
  {
    uid: "1a2b3d4y",
    lat: getRandomLatitude(50000),
    lng: getRandomLongitude(50000),
    foodType: "Thai",
    address: "123 Cuba Street, Miami",
    maxGuestSpots: 5,
    guestSpotsLeft: 3,
    description:
      "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
    image: require("../assets/thai-pad-kra-pao.jpg"),
    price: 60,
    hostDisplayName: "Arisara",
    date: "Jun 30 2024",
    time: "5:30 PM",
  },
];
