export const hostMarkers =
[
    {
        "uid": "1a2b3c4d",
        "lat": -41.286,
        "lng": 174.766,
        "foodType": "Thai",
        "address": "123 Cuba Street, Wellington",
        "maxGuestSpots": 5,
        "guestSpotsLeft": 3,
        "description": "Delicious and aromatic Thai cuisine prepared with authentic ingredients and traditional recipes.",
        "image": require("../assets/thai-pad-kra-pao.jpg"),
        "price": 60,
        "hostDisplayName": "Arisara",
        "date": "Mar 30 2024",
        "time": "5:30 PM"
    },
    {
        "uid": "5e6f7g8h",
        "lat": -41.290,
        "lng": 174.772,
        "foodType": "French",
        "address": "456 Lambton Quay, Wellington",
        "maxGuestSpots": 4,
        "guestSpotsLeft": 2,
        "description": "Exquisite French dishes crafted with finesse and elegance, showcasing the rich culinary heritage of France.",
        "image": require("../assets/thai-pad-kra-pao.jpg"),
        "price": 75,
        "hostDisplayName": "Susie",
        "date": "Apr 01 2024",
        "time": "12:00 PM"
    },
    {
        "uid": "9i0j1k2l",
        "lat": -41.294,
        "lng": 174.773,
        "foodType": "Vietnamese",
        "address": "789 Courtenay Place, Wellington",
        "maxGuestSpots": 6,
        "guestSpotsLeft": 6,
        "description": "Authentic Vietnamese delicacies bursting with flavors, combining fresh herbs, spices, and vibrant ingredients.",
        "image": require("../assets/thai-pad-kra-pao.jpg"),
        "price": 40,
        "hostDisplayName": "Emily",
        "date": "Wed May 01 2024 20:30:00 GMT+1300",
        "time": "5:00 PM"
    },
    {
        "uid": "3m4n5o6p",
        "lat": -41.288,
        "lng": 174.778,
        "foodType": "Colombian",
        "address": "321 Willis Street, Wellington",
        "maxGuestSpots": 3,
        "guestSpotsLeft": 1,
        "description": "Savor the taste of Colombian cuisine, featuring hearty dishes influenced by diverse regional flavors.",
        "image": require("../assets/thai-pad-kra-pao.jpg"),
        "price": 80,
        "hostDisplayName": "Chris",
        "date": "Apr 02 2024",
        "time": "6:15 PM"
    },
    {
        "uid": "7q8r9s0t",
        "lat": -41.285,
        "lng": 174.775,
        "foodType": "Thai",
        "address": "654 Featherston Street, Wellington",
        "maxGuestSpots": 8,
        "guestSpotsLeft": 4,
        "description": "Indulge in the vibrant and spicy flavors of Thai cuisine, prepared with a perfect balance of sweet, sour, and savory.",
        "image": require("../assets/thai-pad-kra-pao.jpg"),
        "price": 50,
        "hostDisplayName": "P Lot",
        "date": "Mar 25 2024",
        "time": "5:45 PM"
    },
    {
        "uid": "1u2v3w4x",
        "lat": -41.283,
        "lng": 174.773,
        "foodType": "French",
        "address": "987 Victoria Street, Wellington",
        "maxGuestSpots": 7,
        "guestSpotsLeft": 7,
        "description": "Experience the artistry of French gastronomy, with refined dishes that showcase culinary mastery and sophistication.",
        "image": require("../assets/thai-pad-kra-pao.jpg"),
        "price": 40,
        "hostDisplayName": "Jean-Pierre",
        "date": "Mar 22 2024",
        "time": "12:30 PM"
    },
    {
        "uid": "5y6z7a8b",
        "lat": -41.282,
        "lng": 174.776,
        "foodType": "Vietnamese",
        "address": "654 Taranaki Street, Wellington",
        "maxGuestSpots": 2,
        "guestSpotsLeft": 2,
        "description": "Discover the fresh and vibrant flavors of Vietnamese cuisine, featuring a harmonious blend of herbs, spices, and textures.",
        "image": require("../assets/thai-pad-kra-pao.jpg"),
        "price": 100,
        "hostDisplayName": "Linh",
        "date": "Mar 29 2024",
        "time": "7:00 PM"
    },
    {
        "uid": "9c0d1e2f",
        "lat": -41.281,
        "lng": 174.774,
        "foodType": "Colombian",
        "address": "321 Ghuznee Street, Wellington",
        "maxGuestSpots": 5,
        "guestSpotsLeft": 0,
        "description": "Taste the authentic flavors of Colombian cuisine, with dishes that reflect the country's diverse cultural influences.",
        "image": require("../assets/thai-pad-kra-pao.jpg"),
        "price": 60,
        "hostDisplayName": "Juan",
        "date": "Mar 20 2024",
        "time": "7:30 PM"
        
    },
    {
        "uid": "3g4h5i6j",
        "lat": -41.280,
        "lng": 174.777,
        "foodType": "Thai",
        "address": "789 Lambton Quay, Wellington",
        "maxGuestSpots": 6,
        "guestSpotsLeft": 3,
        "description": "Experience the bold and aromatic flavors of Thai cuisine, featuring a harmonious blend of spices and fresh ingredients.",
        "image": require("../assets/thai-pad-kra-pao.jpg"),
        "price": 70,
        "hostDisplayName": "Somsak",
        "date": "Mar 19 2024",
        "time": "8:00 PM"
    },
    {
        "uid": "7k8l9m0n",
        "lat": -41.279,
        "lng": 174.775,
        "foodType": "French",
        "address": "456 Cuba Street, Wellington",
        "maxGuestSpots": 4,
        "guestSpotsLeft": 1,
        "description": "Indulge in the elegance of French cuisine, with dishes that showcase culinary finesse and timeless flavors.",
        "image": require("../assets/thai-pad-kra-pao.jpg"),
        "price": 90,
        "hostDisplayName": "Marie",
        "date": "Mar 15 2024",
        "time": "6:30 PM"
    }
]